import type { Project } from "@/types/project"
import { APP_CONFIG } from "@/config"

const STORAGE_KEY = APP_CONFIG.storageKeys.projects

function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 11)}`
}

const now = new Date().toISOString()

function daysFromNow(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().split("T")[0]
}

const SEED_PROJECTS: Project[] = [
  {
    id: generateId(),
    name: "Website Redesign",
    description: "Redesign the company website with modern UI/UX patterns and responsive design.",
    status: "in-progress",
    priority: "high",
    startDate: daysFromNow(-14),
    endDate: daysFromNow(30),
    tags: ["frontend", "design", "ui"],
    tasks: [
      {
        id: generateId(),
        title: "Create wireframes",
        description: "Design wireframes for all major pages",
        status: "done",
        assignee: "Alice",
        dueDate: daysFromNow(-7),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Implement homepage",
        description: "Build the new homepage with hero section and features",
        status: "in-progress",
        assignee: "Bob",
        dueDate: daysFromNow(5),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Mobile responsive",
        description: "Ensure all pages work on mobile devices",
        status: "todo",
        assignee: "Alice",
        dueDate: daysFromNow(14),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "SEO optimization",
        description: "Add meta tags, structured data, and optimize for search engines",
        status: "todo",
        assignee: "",
        dueDate: daysFromNow(20),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Code review - header component",
        description: "Review the new header component implementation",
        status: "review",
        assignee: "Charlie",
        dueDate: daysFromNow(2),
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: generateId(),
    name: "Mobile App v2",
    description: "Build version 2 of the mobile application with new features and performance improvements.",
    status: "planning",
    priority: "urgent",
    startDate: daysFromNow(-3),
    endDate: daysFromNow(60),
    tags: ["mobile", "react-native"],
    tasks: [
      {
        id: generateId(),
        title: "Define app architecture",
        description: "Choose tech stack and define the app architecture",
        status: "in-progress",
        assignee: "Dave",
        dueDate: daysFromNow(3),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Set up CI/CD pipeline",
        description: "Configure automated builds and deployments for iOS and Android",
        status: "todo",
        assignee: "Eve",
        dueDate: daysFromNow(10),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Design system setup",
        description: "Create reusable component library for the mobile app",
        status: "todo",
        assignee: "Alice",
        dueDate: daysFromNow(12),
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: generateId(),
    name: "API Gateway Migration",
    description: "Migrate from legacy API gateway to a modern cloud-native solution.",
    status: "in-progress",
    priority: "high",
    startDate: daysFromNow(-21),
    endDate: daysFromNow(14),
    tags: ["backend", "devops", "cloud"],
    tasks: [
      {
        id: generateId(),
        title: "Audit existing endpoints",
        description: "Document all existing API endpoints and their usage patterns",
        status: "done",
        assignee: "Frank",
        dueDate: daysFromNow(-14),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Set up new gateway",
        description: "Deploy and configure the new API gateway infrastructure",
        status: "done",
        assignee: "Frank",
        dueDate: daysFromNow(-7),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Migrate auth service",
        description: "Move authentication service to the new gateway",
        status: "in-progress",
        assignee: "Grace",
        dueDate: daysFromNow(3),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Load testing",
        description: "Run load tests to ensure the new gateway handles traffic",
        status: "todo",
        assignee: "Frank",
        dueDate: daysFromNow(10),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Update client SDKs",
        description: "Update all client libraries to use new gateway URLs",
        status: "review",
        assignee: "Hank",
        dueDate: daysFromNow(5),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "DNS cutover plan",
        description: "Plan the DNS migration to minimize downtime",
        status: "todo",
        assignee: "Grace",
        dueDate: daysFromNow(12),
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: generateId(),
    name: "Q1 Marketing Campaign",
    description: "Plan and execute the Q1 marketing campaign across all channels.",
    status: "completed",
    priority: "medium",
    startDate: daysFromNow(-45),
    endDate: daysFromNow(-5),
    tags: ["marketing", "campaign"],
    tasks: [
      {
        id: generateId(),
        title: "Create campaign brief",
        description: "Write campaign objectives, audience, and messaging",
        status: "done",
        assignee: "Ivy",
        dueDate: daysFromNow(-40),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Design ad creatives",
        description: "Create banner ads, social posts, and email templates",
        status: "done",
        assignee: "Alice",
        dueDate: daysFromNow(-25),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Launch email campaign",
        description: "Send email blast to subscriber list",
        status: "done",
        assignee: "Ivy",
        dueDate: daysFromNow(-15),
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: generateId(),
    name: "Security Audit",
    description: "Conduct a comprehensive security audit of all systems and fix vulnerabilities.",
    status: "on-hold",
    priority: "urgent",
    startDate: daysFromNow(-10),
    endDate: daysFromNow(20),
    tags: ["security", "compliance"],
    tasks: [
      {
        id: generateId(),
        title: "Vulnerability scanning",
        description: "Run automated scans across all environments",
        status: "done",
        assignee: "Jack",
        dueDate: daysFromNow(-5),
        createdAt: now,
        updatedAt: now,
      },
      {
        id: generateId(),
        title: "Penetration testing",
        description: "Hire external team for pen testing",
        status: "todo",
        assignee: "",
        dueDate: daysFromNow(10),
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
]

/** Call this once on app boot — only seeds if storage is empty. */
export function seedIfEmpty(): void {
  const existing = localStorage.getItem(STORAGE_KEY)
  if (!existing || existing === "[]") {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(SEED_PROJECTS))
  }
}
